name="Tony Stark"
print(name.upper())
print(name.lower())
print(name.find('S'))
print(name.find('k'))
print(name.find('Tony'))
print(name.replace("Tony Stark","Ironman"))
print(name)
print("T" in name+"in Tony Stark")
print("iron" in name+"in Tony Stark")